# Game settings
FPS = 30
WINDOW_WIDTH = 720
WINDOW_HEIGHT = 720
GAME_FIELD_WIDTH = 720
GAME_FIELD_HEIGHT = 720

TANK_WIDTH = 30
TANK_HEIGHT = 30
BULLET_WIDTH = 8
BULLET_HEIGHT = 8
TERRAIN_WIDTH = 36
TERRAIN_HEIGHT = 36
FALCON_WIDTH = 36
FALCON_HEIGHT = 36
FALCON_ID = 50
ENEMY_TANKS_TOTAL_COUNT = 20
MAX_NUMBER_OF_TANKS_AT_ONCE = 5

ENEMY_TANKS_START_POSITIONS = [(0, 0),
                               (int(GAME_FIELD_WIDTH / 2) - TANK_WIDTH, 0),
                               (GAME_FIELD_WIDTH - TANK_WIDTH, 0)]


# Player Tank
PLAYER_TANK_SPEED = 8
PLAYER_TANK_ARMOR = 1
PLAYER_TANK_ATTACK = 1
PLAYER_TANK_BULLET_SPEED = 10
PLAYER_LIVES = 100
PLAYER_ID = 10
PLAYER_FIRE_RATE = 1000


# Armor Tank
ARMOR_TANK_SPEED = 3
ARMOR_TANK_ARMOR = 4
ARMOR_TANK_ATTACK = 1

# Basic Tank
BASIC_TANK_SPEED = 3
BASIC_TANK_ARMOR = 1
BASIC_TANK_ATTACK = 1

# Fast Tank
FAST_TANK_SPEED = 5
FAST_TANK_ARMOR = 1
FAST_TANK_ATTACK = 1

# Power Tank
POWER_TANK_SPEED = 3
POWER_TANK_ARMOR = 1
POWER_TANK_ATTACK = 2

# Bullet
BULLET_WIDTH = 8
BULLET_HEIGHT = 8
BULLET_SPEED = 7

# Player Bullet
PLAYER_BULLET_ID = 100


# Enemy
ENEMY_BULLET_ID = 101
ENEMY_ATTACK = 1

STEEL_ID = 2
STEEL_ARMOR = 10000

BRICK_ID = 1
BRICK_ARMOR = 4
